services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
   image: mongo-express
   container_name: mongo-express
   restart: always
   ports:
     - "8081:8081"
   environment:
     ME_CONFIG_MONGODB_SERVER: mongo
     ME_CONFIG_MONGODB_PORT: 27017
   depends_on:
     - mongo

  webapis:
    build:
      context: .
      dockerfile: WebAPIs/Dockerfile
    container_name: webapis
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5069:5069"

  blazorserver:
    build:
      context: .
      dockerfile: SarasKitchenApp/SarasKitchenApp/Dockerfile
    container_name: blazorserver
    depends_on:
      - webapis
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "7227:7227"

volumes:
  mongodb_data:
