apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  selector:
    app: webapi-app
  ports:
    - port: 5069
      targetPort: 5069
      nodePort: 30069
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi-app
  template:
    metadata:
      labels:
        app: webapi-app
    spec:
      containers:
        - name: webapi-container
          image: saraskitchen-webapis:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5069
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: MONGO__Connection
              value: "mongodb://mongodb-statefulset-0.mongodb:27017/?replicaSet=rs0"
          volumeMounts:
            - name: cert-volume
              mountPath: /https
              readOnly: true
      volumes:
        - name: cert-volume
          secret:
            secretName: https-cert
